--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-02-28 09:26:14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3336 (class 1262 OID 16491)
-- Name: library; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE library WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Ukrainian_Ukraine.1251';


ALTER DATABASE library OWNER TO postgres;

\connect library

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16501)
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    id integer NOT NULL,
    title character varying(100) NOT NULL,
    author character varying(100) NOT NULL,
    year integer NOT NULL,
    person_id integer
);


ALTER TABLE public.book OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16500)
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16493)
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    id integer NOT NULL,
    full_name character varying(100) NOT NULL,
    year_of_birth integer NOT NULL
);


ALTER TABLE public.person OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16492)
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3330 (class 0 OID 16501)
-- Dependencies: 217
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.book (id, title, author, year, person_id) VALUES (1, 'Марсианин', 'Andy Weir', 2016, NULL);
INSERT INTO public.book (id, title, author, year, person_id) VALUES (2, '13 Reasons Why', 'Jay Asher', 2017, NULL);
INSERT INTO public.book (id, title, author, year, person_id) VALUES (3, '501 факт, який треба знати з... історії', 'Елісон Реттл', 2020, NULL);
INSERT INTO public.book (id, title, author, year, person_id) VALUES (4, 'Фактор Черчилля. Як одна людина змінила історію', 'Боріс Джонсон', 2019, 1);
INSERT INTO public.book (id, title, author, year, person_id) VALUES (5, 'Марк Аврелій. Наодинці з собою', 'Марк Аврелій', 2022, 1);
INSERT INTO public.book (id, title, author, year, person_id) VALUES (6, 'Чиста архітектура', 'Мартін Роберт', 2019, NULL);


--
-- TOC entry 3328 (class 0 OID 16493)
-- Dependencies: 215
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.person (id, full_name, year_of_birth) VALUES (1, 'Вакуленко Василь Андрійович', 2001);
INSERT INTO public.person (id, full_name, year_of_birth) VALUES (2, 'Кожедуб Андрій Миколайович', 1996);
INSERT INTO public.person (id, full_name, year_of_birth) VALUES (3, 'Захвора Василь Олександрович', 1999);
INSERT INTO public.person (id, full_name, year_of_birth) VALUES (4, 'Павлов Максим Генадійович', 2002);


--
-- TOC entry 3337 (class 0 OID 0)
-- Dependencies: 216
-- Name: book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.book_id_seq', 3, true);


--
-- TOC entry 3338 (class 0 OID 0)
-- Dependencies: 214
-- Name: person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_id_seq', 2, true);


--
-- TOC entry 3183 (class 2606 OID 16505)
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id);


--
-- TOC entry 3179 (class 2606 OID 16499)
-- Name: person person_full_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_full_name_key UNIQUE (full_name);


--
-- TOC entry 3181 (class 2606 OID 16497)
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- TOC entry 3184 (class 2606 OID 16506)
-- Name: book book_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE SET NULL;


-- Completed on 2023-02-28 09:26:14

--
-- PostgreSQL database dump complete
--

